version: "1.0"
services:
    mysql:
        image: mysql
        container_name: wordpress_db
        volumes:
            - 'data:/var/lib/mysql'
        environment:
            - MYSQL_ROOT_PASSWORD=pass
            - MYSQL_DATABASE=wordpressdb
            - MYSQL_USER=wordpress
            - MYSQL_PASSWORD=wordpress
        expose:
            - 3306
            - 33060
        networks: 
            - my_network
    wordpress:
        container_name: wordpress-website
        image: wordpress
        volumes: 
            - 'wp_data:/var/www/html'
        ports:
            - 80:80
        environment:
            - WORDPRESS_DB_HOST=wordpress_db
            - WORDPRESS_DB_USER=wordpress
            - WORDPRESS_DB_PASSWORD=wordpress
            - WORDPRESS_DB_NAME=wordpressdb
        networks:
            - my_network
volumes:
    data:
    wp_data: 
networks:
    my_network: